log_level: "info"
mode: "full" # full, light, boot
network:
  ip_address: "0.0.0.0"
  max_peers: 50
dht:
  mode: "server"
  bootstrap_peers:
    - "/ip4/172.20.0.2/tcp/12000/p2p/12D3KooWDZNQvpy2oM979kqFsEA8KykScP9GB4noNDpcJQjtBbY2"
